server:
  port: 8001
spring:
  application:
    name: user-management
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: LOCAL
    password: root
    driver-class-name: oracle.jdbc.OracleDriver
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
